const actionTypes={
    FETCH_STUDENTS_START:"FETCH_STUDENTS_START",
    FETCH_STUDENTS_SUCCESS:"FETCH_STUDENTS_SUCCESS",
    FETCH_STUDENTS_FAIL:"FETCH_STUDENTS_FAIL",
    ADD_STUDENT:"ADD_STUDENT",
    DELETE_STUDENT:"DELETE_STUDENT",
    UPDATE_STUDENT:"UPDATE_STUDENT"
}



export default actionTypes